### ISSUE TITLE
Password Escaping 1.8.2

### ISSUE THREAD

**Issue by battlecow** [JFrogDev/bamboo-artifactory-plugin#16]
We upgraded our plugin to the newest version (1.8.2) and found that the password escaping mechanism has issues with at least the '%' character and throws a 500 error in Bamboo if a password contains this character.  I am unaware of other characters that might cause an issue but this is the one we ran into.

**Comment by shikloshi** [comment]
Hi @battlecow,

Thanks for reporting this issue.
I've opened a [Jira ticket](https://www.jfrog.com/jira/browse/BAP-306) for this issue and you can download from there the snapshot version with this issue fix (on top of version 1.8.2) and follow up on any updates.

Note that this is a snapshot version and not fully tests.
Please let us know if there are any issues with the fix.

Thanks,
Aviad.

**Comment by battlecow** [comment]
We ended up changing the password on Artifactory and went through and updated all of our build plans, however I can verify the fix on our dev instance if you want?

**Comment by shikloshi** [comment]
Hi @battlecow , I have verified it locally on my environment. If you worked around that issue then great. We will QA this as part of the next release.

Thanks,
Aviad.

**Comment by battlecow** [comment]
Great, thanks for looking at this so quickly, we appreciate the work on this plugin!
