### ISSUE TITLE
Issue since upgrading to latest 1.10 plugin

### ISSUE THREAD

**Issue by cfsbhawkins** [JFrogDev/bamboo-artifactory-plugin#27]
I am on latest Bamboo, and it seems that my build projects that have artifactory deployments fail. With the following error 

FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\xxx\AppData\Local\Temp\artifactory.init.script8973987296758838010gradle' line: 1

* What went wrong:
Could not compile initialization script 'C:\Users\NOC\AppData\Local\Temp\artifactory.init.script8973987296758838010gradle'.
> startup failed:
  initialization script 'C:\Users\xxx\AppData\Local\Temp\artifactory.init.script8973987296758838010gradle': 1: unable to resolve class org.jfrog.gradle.plugin.artifactory.ArtifactoryConfigurationsPlugin
@ line 1, column 1.
     import org.jfrog.gradle.plugin.artifactory.ArtifactoryConfigurationsPlugin
     ^
  
  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Projects that just use the plugin to compile without any tie in to artifactory work just fine.

**Comment by eyalbe4** [comment]
Thanks so much for reporting this @cfsbhawkins.
Can you please confirm that installing the below snapshot version resolve this issue?
If it does, we'll issue a new release.
Here's the download link for the version with the fix:
https://oss.jfrog.org/artifactory/oss-snapshot-local/org/jfrog/bamboo/bamboo-artifactory-plugin/1.10.x-SNAPSHOT/bamboo-artifactory-plugin-1.10.x-20160329.114743-1.jar

**Comment by cfsbhawkins** [comment]
@eyalbe4 No go still new error, this is an android project so I get the following error when you apply the Java Plugin with the init script

30-Mar-2016 09:03:11	Cannot publish pom for project ':' since it does not contain the Maven plugin install task and task ':artifactoryPublish' does not specify a custom pom path.
30-Mar-2016 09:03:11	Cannot publish pom for project ':app' since it does not contain the Maven plugin install task and task ':app:artifactoryPublish' does not specify a custom pom path.
30-Mar-2016 09:03:11	Cannot publish pom for project ':roninmaps' since it does not contain the Maven plugin install task and task ':roninmaps:artifactoryPublish' does not specify a custom pom path.
30-Mar-2016 09:03:11	Cannot publish pom for project ':vlc' since it does not contain the Maven plugin install task and task ':vlc:artifactoryPublish' does not specify a custom pom path.
30-Mar-2016 09:03:14	
30-Mar-2016 09:03:14	FAILURE: Build failed with an exception.
30-Mar-2016 09:03:14	
30-Mar-2016 09:03:14	* What went wrong:
30-Mar-2016 09:03:14	A problem occurred configuring project ':app'.
30-Mar-2016 09:03:14	> The 'java' plugin has been applied, but it is not compatible with the Android plugins.
30-Mar-2016 09:03:14	
30-Mar-2016 09:03:14	* Try:
30-Mar-2016 09:03:14	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I am running Gradle 2.9 as if I go any higher I get the following error, It appears someone not sure if its the artifactory plugin or bamboo, but they are doing a string compare instead of an double compare of the version number.

	* What went wrong:
28-Mar-2016 14:21:47	A problem occurred evaluating project ':app'.
28-Mar-2016 14:21:47	> Failed to apply plugin [id 'com.android.application']
28-Mar-2016 14:21:47	   > Gradle version 2.2 is required. Current version is 2.12. If using the gradle wrapper, try editing the distributionUrl in C:\Users\xxx\bamboo-agent-home\xml-data\build-dir\xxx-xxxxx-JOB1\gradle\wrapper\gradle-wrapper.properties to gradle-2.2-all.zip

**Comment by eyalbe4** [comment]
@cfsbhawkins, the Bamboo Artifactory Plugin applies the java plugin to your gradle build script behind the scenes. There's a chance that the default java plugin is not compatible with the Android Plugin you are using. We might need to stop applying the java plugin. As a result, non-Android build scripts will need to apply the java plugin manually to their build scripts. We'll soon share another snapshot version of the plugin which avoids applying the java plugin.

**Comment by eyalbe4** [comment]
@cfsbhawkins, we opened [this](https://www.jfrog.com/jira/browse/BAP-345) Jira issue and created a snapshot version that should fix the error you reported when your build uses the Android Plugin. We would appreciate your feedback for it.
You can download the snapshot version from [here](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/jfrog/bamboo/bamboo-artifactory-plugin/1.10.x-SNAPSHOT/bamboo-artifactory-plugin-1.10.x-20160404.131403-3.jar)

**Comment by cfsbhawkins** [comment]
@eyalbe4 That fixed it, thanks again!

**Comment by eyalbe4** [comment]
Thanks @cfsbhawkins! We'll soon release this fix.

**Comment by eyalbe4** [comment]
Bamboo Artifactory Plugin 1.10.1 with this fix has been released.
