### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by jaredpetersen** [JFrogDev/bamboo-artifactory-plugin#30]
Add a license file to the repository to indicate how the source code is licensed. The [documentation website](https://www.jfrog.com/confluence/display/RTF/Bamboo+Artifactory+Plug-in) indicates that the code is available under the Apache v2 License but there isn't any indication of that in the code. Other JFrog repositories do include a license file: [artifactory-scripts](https://github.com/JFrogDev/artifactory-scripts), [cocoapods-art](https://github.com/JFrogDev/cocoapods-art), [bitbucket-bintray-plugin](https://github.com/JFrogDev/bitbucket-bintray-plugin), etc.

**Comment by eyalbe4** [comment]
@jaredpetersen,
We added the license file to this repository. Will add it to the other repositories soon. Thanks.

**Comment by jaredpetersen** [comment]
@eyalbe4 Great! I'll close this issue then.
