### ISSUE TITLE
Support for Bamboo 5.14.x

### ISSUE THREAD

**Issue by tdillon** [JFrogDev/bamboo-artifactory-plugin#32]
Can you add support for version 5.14.x of Bamboo?  Currently the latest version of Bamboo that is supported is 5.13.2 by version 1.11.2 of the plugin.

**Comment by eyalbe4** [comment]
We're currently working on plugin version compatible with Bamboo 5.14 @tdillon.
Version 5.14 includes a few changes to the VCS Repositories APIs, which broke the Release Staging feature.

**Comment by tdillon** [comment]
@eyalbe4 is your release schedule public?  We are performing a Bamboo upgrade and this plugin may be a potential blocker.

**Comment by eyalbe4** [comment]
@tdillon, we aim to release the compatibility fix by the end of next week, but we're working hard to release it sooner.

**Comment by eyalbe4** [comment]
@tdillon, version 1.12.0 with Bamboo 5.14.x VCS Repositories API compatibility fixes has been released.

**Comment by tdillon** [comment]
Thanks for the quick turnaround.
