### ISSUE TITLE
java.lang.NullPointerException on Generic deploy - Bamboo 5.14.3.1

### ISSUE THREAD

**Issue by giulio1979** [JFrogDev/bamboo-artifactory-plugin#34]
simple	08-Jan-2017 11:59:07	Bamboo Artifactory Plugin version: 2.0.0
simple	08-Jan-2017 11:59:07	For pattern: packages/rpm/*.rpm 2 artifacts were found
error	08-Jan-2017 11:59:07	Exception occurred while executing task
error	08-Jan-2017 11:59:07	java.lang.NullPointerException
error	08-Jan-2017 11:59:07		at org.jfrog.bamboo.util.generic.GenericBuildInfoHelper.getDynamicPropertyMap(GenericBuildInfoHelper.java:153)
error	08-Jan-2017 11:59:07		at org.jfrog.bamboo.util.generic.GenericBuildInfoHelper.createDeployDetailsAndAddToBuildInfo(GenericBuildInfoHelper.java:138)
error	08-Jan-2017 11:59:07		at org.jfrog.bamboo.task.ArtifactoryGenericDeployTask.deploy(ArtifactoryGenericDeployTask.java:186)
error	08-Jan-2017 11:59:07		at org.jfrog.bamboo.task.ArtifactoryGenericDeployTask.execute(ArtifactoryGenericDeployTask.java:111)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$2(TaskExecutorImpl.java:313)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:246)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:313)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:122)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:74)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:215)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:139)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:130)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:221)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:129)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:137)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:51)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
error	08-Jan-2017 11:59:07		at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
error	08-Jan-2017 11:59:07		at java.lang.Thread.run(Thread.java:745)
simple	08-Jan-2017 11:59:07	Finished task 'Deploy RPM Packages for develop branches' with result: Error

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @giulio1979.
We opened [BAP-369](https://www.jfrog.com/jira/browse/BAP-369) to track this fix. We'll soon publish a snapshot version with the fix.

**Comment by eyalbe4** [comment]
@giulio1979,
Here's a download link of snapshot version with the fix:
https://oss.jfrog.org/oss-snapshot-local/org/jfrog/bamboo/bamboo-artifactory-plugin/2.0.x-SNAPSHOT/bamboo-artifactory-plugin-2.0.x-SNAPSHOT.jar
We'd appreciate your feedback for it.

**Comment by giulio1979** [comment]
Publishing worked fine now, thanks for the support !
