### ISSUE TITLE
NullPointerException in org.jfrog.bamboo.util.generic.GenericBuildInfoHelper.getDynamicPropertyMap

### ISSUE THREAD

**Issue by markuslohn** [JFrogDev/bamboo-artifactory-plugin#36]
Configured Artifactory Deploy Task in Bamboo Build Plan. When executing a NullPointerException is thrown. A screenshot with the configuration of the task and the log output is attached.
<img width="1173" alt="screen shot 2017-01-18 at 15 34 39" src="https://cloud.githubusercontent.com/assets/25202280/22067982/caccac12-dd93-11e6-91e5-a48ef9d46ec5.PNG">
<img width="1432" alt="screen shot 2017-01-18 at 15 34 12" src="https://cloud.githubusercontent.com/assets/25202280/22067983/caf09154-dd93-11e6-8585-936cb8933192.PNG">

**Comment by eyalbe4** [comment]
@markuslohn, till a new plugin version is released with a fix for this issue, you can use the snapshot version referenced in this issue:
https://github.com/JFrogDev/bamboo-artifactory-plugin/issues/34
