### ISSUE TITLE
Support for Bamboo 6.0.x

### ISSUE THREAD

**Issue by tdillon** [JFrogDev/bamboo-artifactory-plugin#40]
Can you add support for version 6.0.x of Bamboo? Currently the latest version of Bamboo that is supported is 5.15.x by version 2.0.2 of the plugin.

**Comment by mebibou** [comment]
Anyone has an alternative for Bamboo 6 before they release a new version?

**Comment by eyalbe4** [comment]
We are not aware of any compatibility issue between the latest Artifactory Plugin version and Bamboo 6. If you do see any breaking issue, please let us know and we'll release a compatible version.

**Comment by mebibou** [comment]
@eyalbe4 could you then release a compatible version so we can install directly from the add-ons section?

**Comment by tdillon** [comment]
Version 2.1.1 is compatible with Bamboo 6.0.x.  Thanks.
