### ISSUE TITLE
Generic deploy NullPointerException when build triggered as child plan

### ISSUE THREAD

**Issue by KyleMcIntire** [JFrogDev/bamboo-artifactory-plugin#50]
When using the Artifactory Generic Deploy task from a plan triggered from a parent plan I receive the following error:
```
simple	28-Nov-2017 14:16:15	Starting task 'Deploy' of type 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryGenericTask'
simple	28-Nov-2017 14:16:15	Bamboo Artifactory Plugin version: 2.3.0
simple	28-Nov-2017 14:16:16	For pattern: /root/bamboo-agent-home/xml-data/build-dir/PLAY-HC0-JOB1/*.txt 1 artifacts were found.
simple	28-Nov-2017 14:16:16	Deploying artifact: https://artifactory.jamf.build/artifactory/libs-snapshot-local/HC-891/develop/test.txt
error	28-Nov-2017 14:16:16	Exception occurred while executing task
error	28-Nov-2017 14:16:16	java.lang.NullPointerException
error	28-Nov-2017 14:16:16		at java.net.URLEncoder.encode(URLEncoder.java:204)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.util.DeploymentUrlUtils.encode(DeploymentUrlUtils.java:80)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.util.DeploymentUrlUtils.buildMatrixParamsString(DeploymentUrlUtils.java:71)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.createHttpPutMethod(ArtifactoryBuildInfoClient.java:708)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:644)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:344)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.deploy(SpecsHelper.java:308)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:65)
error	28-Nov-2017 14:16:16		at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:73)
error	28-Nov-2017 14:16:16		at org.jfrog.bamboo.task.ArtifactoryGenericDeployTask.deployByFileSpec(ArtifactoryGenericDeployTask.java:202)
error	28-Nov-2017 14:16:16		at org.jfrog.bamboo.task.ArtifactoryGenericDeployTask.execute(ArtifactoryGenericDeployTask.java:126)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$2(TaskExecutorImpl.java:282)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:223)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:282)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:118)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:71)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:185)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:120)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:113)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:185)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:113)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:126)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:47)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
error	28-Nov-2017 14:16:16		at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
error	28-Nov-2017 14:16:16		at java.lang.Thread.run(Thread.java:748)
simple	28-Nov-2017 14:16:16	Finished task 'Deploy' with result: Error
```

Error was not reproducible on the main plan branch - only on an added plan branch. In this case, I added develop to each of the plans. Running the develop parent plan causes the child develop plan to fail.

Attached are the results from develop child plan # 11 (successful) and develop child plan # 12 (failure). Additionally, I have attached a diff between the two log files. I cleaned up the logs to show the plan variables on separate lines with spacing between the variables and the values and sorted so that wdiff could compare them meaningfully.

[logs.zip](https://github.com/JFrogDev/bamboo-artifactory-plugin/files/1511836/logs.zip)

Let me know if I can provide additional info.

**Comment by yahavi** [comment]
@KyleMcIntire,
Thanks for reporting this issue!
We opened [BAP-417](https://www.jfrog.com/jira/browse/BAP-417) to track this task.
There you can find a snapshot which includes a fix.

**Comment by KyleMcIntire** [comment]
@yahavi - I have upgraded our bamboo artifactory plugin in our staging environment with this fix. Everything looks good! We will be rolling this snapshot to production the next time we restart our bamboo instance.

**Comment by yahavi** [comment]
@KyleMcIntire,
Thanks for the update!
Bamboo Artifactory Plug-in v2.4.0 had been released.
Feel free to upgrade.

**Comment by KyleMcIntire** [comment]
After having this snapshot (and now v2.4.0) in production we have been running into threading issues with bamboo which has caused multiple bamboo outages per day which has brought our development pipelines to a halt.

We have been working with atlassian on this issue and they identified the potential culprit for the threading issue to be this plugin.

Here is their comment:

> Many of your slow threads where gathering simple build result data from the database
> The old OOM errors were caused by the excessive threads, not the other way around (you probably knew that)
> There were some threads taking until 30min to get build logs or even show the commit details
> ```
> 31 min running: Thread "http-nio-8085-exec-177" (id=68532) https://bamboo.jamf.build/browse/AUT-JWT-TE-1096
> 26 min running: Thread "http-nio-8085-exec-184" (id=68539) https://bamboo.jamf.build/browse/JSS-JU853-UT2-24/log
> 27 min running: Thread "http-nio-8085-exec-80"  (id=361)   https://bamboo.jamf.build/browse/JSS-JSSNOUP2712-IT6-35/commit
> ```
> When investigating the http-nio-8085-exec-177, for example, this is what Kah Loun Foong saw:
> ```
> 16-Jan-2018 10:06:01.221 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.valves.StuckThreadDetectionValve.notifyStuckThreadDetected Thread "http-nio-8085-exec-177" (id=68532) has been active for 61,465 milliseconds (since 1/16/18 10:04 AM) to serve the same request for https://bamboo.jamf.build/browse/AUT-JWT-TE-1096 and may be stuck (configured threshold for this StuckThreadDetectionValve is 60 seconds). There is/are 2 thread(s) in total that are monitored by this Valve and may be stuck.
> ```
> ```
>  java.lang.Throwable
>   at java.net.SocketInputStream.socketRead0(Native Method)
>   at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
>   at java.net.SocketInputStream.read(SocketInputStream.java:171)
>   at java.net.SocketInputStream.read(SocketInputStream.java:141)
>   ...
>   at com.atlassian.bamboo.plan.PlanManagerImpl.getAllPlans(PlanManagerImpl.java:201)
>   ...
>   at com.sun.proxy.$Proxy408.getAllPlans(Unknown Source)
>   at org.jfrog.bamboo.buildinfo.action.condition.BuildInfoActionCondition.shouldDisplay(BuildInfoActionCondition.java:49)
>   ...
> ```
> Please notice that in the last line there is the JFrog plugin causing the call to get all plans in Bamboo. You have about 18876 plan/(plan branches) which causes a lot of load to Bamboo and the database server. This pattern happens to lots of calls involving build results.
> 
> Do you think you guys can temporarily disable the JFrog plugin temporarily?
> That should be the cause of the whole issue.
> 
> Did you guys had any recent change in this plugin, update or even installed it recently?

We are going to try downgrading the plugin to an older version to see if this issue still persists. Please consider this an urgent issue.

**Comment by KyleMcIntire** [comment]
Downgrading the plugin to v2.3.0 has resolved the threading issues.

**Comment by eyalbe4** [comment]
Thanks for sharing this information @KyleMcIntire. 
This is probably the commit which causes the load on Bamboo:
https://github.com/JFrogDev/bamboo-artifactory-plugin/commit/fb0c23a4b57feb423c77653460e6ba7d0a8a388f
The Bamboo API used there should probably be replaced with a more efficient one. 
Can you please share this commit with the guys from Atlassian who identified the root cause? I'm sure that they could help us by suggesting the best API to use.
While they respond, we'll also be searching the Bamboo sources for a solution.
Thanks

**Comment by DimaNevelev** [comment]
@KyleMcIntire,
Bamboo Artifactory Plug-in v2.4.1 has been released.
In this version we replaced the load causing API. 
Can you please confirm that this solves the performance issue?

**Comment by KyleMcIntire** [comment]
Thanks for the quick turnaround! Upgraded to v2.4.1, initial testing (loading job level details) is looking good. We will be monitoring performance throughout the day tomorrow when we see the heaviest load.

**Comment by KyleMcIntire** [comment]
Performance is looking improved and the original issue this was created for is no longer appearing. Closing out this issue, thank you!
